### ISSUE TITLE
Tile Creation Issue

### ISSUE THREAD

**Issue by Teku-Guy** [Teku-Guy/finalProject#4]
After consulting my math teacher. Jessus you made something wrong when you create the tile object the width and height.The width is pre define so thats why there is space when you spawn in the grass blocks.

**Comment by JessusALK** [comment]
Ya I know about that issue I just haven't worked on it

**Comment by JLandFish** [comment]
Gustavo you got pwnd

**Comment by Teku-Guy** [comment]
Well try to fix it

**Comment by Teku-Guy** [comment]
I figured another Issue. You can still go through the blocks and the blocks can spawn fine with no lag but you can go through them after 3 or 5 blocks if you walk on top of the and you also go through the ones that stop you from going down if either you hold the "S" key or you press it rapidly. @JessusALK
